apiVersion: apps/v1
kind: Deployment
metadata:
  annotations: {}
  labels:
    workload.user.cattle.io/workloadselector: apps.deployment-default-mealy
    env: prod
  name:-mealy
spec:
  replicas: 5
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: apps.deployment-default-mealy
  template:
    metadata:
      labels:
        workload.user.cattle.io/workloadselector: apps.deployment-default-mealy
        env: prod
    spec:
      containers:
      - image: markusdhs/mealy:latest
        imagePullPolicy: Always
        name: container-0
        ports:
        - containerPort: 80
          name: test
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
